name: 'Install PMD'
author: Steve Babula - forked from Matias Kruk
description: 'This action installs and configures PMD Source Code Analyzer for use within GitHub Actions.'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
